write_global_param <- function(path_sim, syear, eyear, timestep = 24, output_force = TRUE, model = "hbv") {
  
  library(GetoptLong)
  
  filename <- file.path(path_sim, "/params/global_param")
  
  qqcat("#######################################################################\n", file = filename, append = FALSE)
  qqcat("# VIC Model Parameters - 4.1.x\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# $Id: global.param.sample,v 5.7.2.27 2012/02/07 19:03:02 vicadmin Exp $\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Simulation Parameters\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("NLAYER		3	# number of soil layers\n", file = filename, append = TRUE)
  qqcat("NODES		3	# number of soil thermal nodes \n", file = filename, append = TRUE)
  qqcat("TIME_STEP 	@{timestep}	# model time step in hours (set to 24 if FULL_ENERGY = FALSE, set to < 24 if FULL_ENERGY = TRUE)\n", file = filename, append = TRUE)
  qqcat("SNOW_STEP	@{timestep}	# time step in hours for which to solve the snow model (should = TIME_STEP if TIME_STEP < 24)\n", file = filename, append = TRUE)
  qqcat("STARTYEAR	@{syear}	# year model simulation starts\n", file = filename, append = TRUE)
  qqcat("STARTMONTH	01	# month model simulation starts\n", file = filename, append = TRUE)
  qqcat("STARTDAY	01 	# day model simulation starts\n", file = filename, append = TRUE)
  qqcat("STARTHOUR	00	# hour model simulation starts\n", file = filename, append = TRUE)
  qqcat("ENDYEAR 	@{eyear}	# year model simulation ends\n", file = filename, append = TRUE)
  qqcat("ENDMONTH	12	# month model simulation ends\n", file = filename, append = TRUE)
  qqcat("ENDDAY		31	# day model simulation ends\n", file = filename, append = TRUE)
  qqcat("FULL_ENERGY 	FALSE	# TRUE = calculate full energy balance; FALSE = compute water balance only\n", file = filename, append = TRUE)
  qqcat("FROZEN_SOIL	FALSE	# TRUE = calculate frozen soils\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Soil Temperature Parameters\n", file = filename, append = TRUE)
  qqcat("# VIC will choose appropriate values for QUICK_FLUX and IMPLICIT depending on values of FULL_ENERGY and FROZEN_SOIL; the user should only need to override VICs choices in special cases.\n", file = filename, append = TRUE)
  qqcat("# The other options in this section are only applicable when FROZEN_SOIL is TRUE and their values depend on the appliqqcation.\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("#QUICK_FLUX	FALSE	# TRUE = use simplified ground heat flux method of Liang et al (1999); FALSE = use finite element method of Cherkauer et al (1999)\n", file = filename, append = TRUE)
  qqcat("#IMPLICIT	TRUE	# TRUE = use implicit solution for soil heat flux equation of Cherkauer et al (1999), otherwise uses original explicit solution.\n", file = filename, append = TRUE)
  qqcat("#QUICK_SOLVE	FALSE	# TRUE = Use Liang et al., 1999 formulation for iteration, but explicit finite difference method for final step.\n", file = filename, append = TRUE)
  qqcat("#NO_FLUX		FALSE	# TRUE = use no flux lower boundary for ground heat flux computation; FALSE = use constant flux lower boundary condition.  If NO_FLUX = TRUE, QUICK_FLUX MUST = FALSE\n", file = filename, append = TRUE)
  qqcat("#EXP_TRANS	FALSE	# TRUE = exponentially distributes the thermal nodes in the Cherkauer et al. (1999) finite difference algorithm, otherwise uses linear distribution\n", file = filename, append = TRUE)
  qqcat("#GRND_FLUX_TYPE	GF_410	# Options for ground flux:\n", file = filename, append = TRUE)
  qqcat("#			# GF_406 = use (flawed) formulas for ground flux, deltaH, and fusion from VIC 4.0.6 and earlier;\n", file = filename, append = TRUE)
  qqcat("#			# GF_410 = use formulas from VIC 4.1.0 (ground flux, deltaH, and fusion are correct; deltaH and fusion ignore surf_atten);\n", file = filename, append = TRUE)
  qqcat("#			# Default = GF_410\n", file = filename, append = TRUE)
  qqcat("#TFALLBACK	TRUE	# TRUE = when temperature iteration fails to converge, use previous time steps T value\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Precip (Rain and Snow) Parameters\n", file = filename, append = TRUE)
  qqcat("# Generally these default values do not need to be overridden\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("#SNOW_ALBEDO	USACE	# USACE = use traditional VIC algorithm based on US Army Corps of Engineers empirical snow albedo decay curves, using hard-coded dates for transitions from snow accumulation to melting; SUN1999 = use algorithm of Sun et al 1999, in which albedo decay depends on snow cold content (more appropriate for simulations outside the US).\n", file = filename, append = TRUE)
  qqcat("#SNOW_DENSITY	DENS_BRAS	# DENS_BRAS = use traditional VIC algorithm taken from Bras, 1990; DENS_SNTHRM = use algorithm taken from SNTHRM model.\n", file = filename, append = TRUE)
  qqcat("#BLOWING		FALSE	# TRUE = compute evaporative fluxes due to blowing snow\n", file = filename, append = TRUE)
  qqcat("#COMPUTE_TREELINE	FALSE	# Can be either FALSE or the id number of an understory veg class; FALSE = turn treeline computation off; VEG_CLASS_ID = replace any overstory veg types with the this understory veg type in all snow bands for which the average July Temperature <= 10 C (e.g. COMPUTE_TREELINE 10 replaces any overstory veg cover with class 10)\n", file = filename, append = TRUE)
  qqcat("#DIST_PRCP	FALSE	# TRUE = use distributed precipitation\n", file = filename, append = TRUE)
  qqcat("#PREC_EXPT	0.6	# exponent for use in distributed precipitation eqn (only used if DIST_PRCP is TRUE)\n", file = filename, append = TRUE)
  qqcat("#CORRPREC	FALSE	# TRUE = correct precipitation for gauge underqqcatch\n", file = filename, append = TRUE)
  qqcat("#MAX_SNOW_TEMP	0.5	# maximum temperature (C) at which snow can fall\n", file = filename, append = TRUE)
  qqcat("#MIN_RAIN_TEMP	-0.5	# minimum temperature (C) at which rain can fall\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Turbulent Flux Parameters\n", file = filename, append = TRUE)
  qqcat("# Generally these default values do not need to be overridden\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("#MIN_WIND_SPEED	0.1	# minimum allowable wind speed (m/s)\n", file = filename, append = TRUE)
  qqcat("#AERO_RESIST_CANSNOW	AR_406_FULL	# Options for aerodynamic resistance in snow-filled canopy:\n", file = filename, append = TRUE)
  qqcat("#			# AR_406 	= multiply by 10 for latent heat but do NOT multiply by 10 for sensible heat and do NOT apply stability correction (as in VIC 4.0.6); when no snow in canopy, use surface aero_resist for ET.\n", file = filename, append = TRUE)
  qqcat("#			# AR_406_LS 	= multiply by 10 for latent heat AND sensible heat and do NOT apply stability correction; when no snow in canopy, use surface aero_resist for ET.\n", file = filename, append = TRUE)
  qqcat("#			# AR_406_FULL 	= multiply by 10 for latent heat AND sensible heat and do NOT apply stability correction; additionally, always use overstory aero_resist for ET (as in 4.1.0).\n", file = filename, append = TRUE)
  qqcat("#			# AR_410 	= apply stability correction but do NOT multiply by 10 (as in VIC 4.1.0); additionally, always use overstory aero_resist for ET (as in 4.1.0).\n", file = filename, append = TRUE)
  qqcat("#			# Default 	= AR_406_FULL\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Meteorological Forcing Disaggregation Parameters\n", file = filename, append = TRUE)
  qqcat("# Generally these default values do not need to be overridden\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("#PLAPSE		TRUE	# This controls how VIC computes air pressure when air pressure is not supplied as an input forcing: TRUE = set air pressure to sea level pressure, lapsed to grid cell average elevation; FALSE = set air pressure to constant 95.5 kPa (as in all versions of VIC pre-4.1.1)\n", file = filename, append = TRUE)
  qqcat("#SW_PREC_THRESH		0	# Minimum daily precip [mm] that can cause dimming of incoming shortwave; default = 0.\n", file = filename, append = TRUE)
  qqcat("MTCLIM_SWE_CORR	FALSE    # This controls VICs estimates of incoming shortwave in the presence of snow; TRUE = adjust incoming shortwave for snow albedo effect; FALSE = do not adjust shortwave; default = TRUE\n", file = filename, append = TRUE)
  qqcat("#VP_ITER		VP_ITER_ALWAYS	# This controls VICs iteration between estimates of shortwave and vapor pressure:\n", file = filename, append = TRUE)
  qqcat("#			# VP_ITER_NEVER = never iterate; make estimates separately\n", file = filename, append = TRUE)
  qqcat("#			# VP_ITER_ALWAYS = always iterate once\n", file = filename, append = TRUE)
  qqcat("#			# VP_ITER_ANNUAL = iterate once for arid climates based on annual Precip/PET ratio\n", file = filename, append = TRUE)
  qqcat("#			# VP_ITER_CONVERGE = iterate until shortwave and vp stabilize\n", file = filename, append = TRUE)
  qqcat("#			# default = VP_ITER_ALWAYS\n", file = filename, append = TRUE)
  qqcat("#VP_INTERP	TRUE	# This controls sub-daily humidity estimates; TRUE = interpolate daily VP estimates linearly between sunrise of one day to the next; FALSE = hold VP constant for entire day\n", file = filename, append = TRUE)
  qqcat("#LW_TYPE		LW_TVA	# This controls the algorithm used to estimate clear-sky longwave radiation:\n", file = filename, append = TRUE)
  qqcat("#			# LW_TVA = Tennessee Valley Authority algorithm (1972)\n", file = filename, append = TRUE)
  qqcat("#			# other options listed in vicNl_def.h\n", file = filename, append = TRUE)
  qqcat("#			# default = LW_TVA (this was also the traditional VIC algorithm)\n", file = filename, append = TRUE)
  qqcat("#LW_CLOUD	LW_CLOUD_DEARDORFF	# This controls the algorithm used to estimate the influence of clouds on total longwave:\n", file = filename, append = TRUE)
  qqcat("#			# LW_CLOUD_BRAS = method from Bras textbook (this was the traditional VIC algorithm)\n", file = filename, append = TRUE)
  qqcat("#			# LW_CLOUD_DEARDORFF = method of Deardorff (1978)\n", file = filename, append = TRUE)
  qqcat("#			# default = LW_CLOUD_DEARDORFF\n", file = filename, append = TRUE)
  qqcat("OUTPUT_FORCE	@{output_force}\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Miscellaneous Simulation Parameters\n", file = filename, append = TRUE)
  qqcat("# Generally these default values do not need to be overridden\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("#CONTINUEONERROR	TRUE	# TRUE = if simulation aborts on one grid cell, continue to next grid cell\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# State Files and Parameters\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("#INIT_STATE	/home/jmg/VIC-master/12.70/params/vic/state/STEHE.state_19481231	# Initial state path/file\n", file = filename, append = TRUE)
  qqcat("#STATENAME	/home/jmg/VIC-master/12.70/state/STEHE.state	# Output state file path/prefix.  The date (STATEYEAR,STATEMONTH,STATEDAY) will be appended to the prefix automatically in the format yyyymmdd.\n", file = filename, append = TRUE)
  qqcat("#STATEYEAR	2000	# year to save model state\n", file = filename, append = TRUE)
  qqcat("#STATEMONTH	12	# month to save model state\n", file = filename, append = TRUE)
  qqcat("#STATEDAY	31	# day to save model state\n", file = filename, append = TRUE)
  qqcat("#BINARY_STATE_FILE       FALSE	# TRUE if state file should be binary format; FALSE if ascii\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Forcing Files and Parameters\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#       All FORCING filenames are actually the pathname, and prefix\n", file = filename, append = TRUE)
  qqcat("#               for gridded data types: ex. DATA/forcing_\n", file = filename, append = TRUE)
  qqcat("#               Latitude and longitude index suffix is added by VIC\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#	There must be 1 FORCE_TYPE entry for each variable (column) in the forcing file\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#	If FORCE_TYPE is BINARY, each FORCE_TYPE must be followed by:\n", file = filename, append = TRUE)
  qqcat("#			SIGNED/UNSIGNED	SCALE_FACTOR\n", file = filename, append = TRUE)
  qqcat("#		For example (BINARY):\n", file = filename, append = TRUE)
  qqcat("#			FORCE_TYPE	PREC	UNSIGNED	40\n", file = filename, append = TRUE)
  qqcat("#		or (ASCII):\n", file = filename, append = TRUE)
  qqcat("#			FORCE_TYPE	PREC\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#FORCING1	/home/jmg/VIC-master/testdata2/forcing/data_	# Forcing file path and prefix\n", file = filename, append = TRUE)
  qqcat("#N_TYPES     4\n", file = filename, append = TRUE)
  qqcat("#FORCE_TYPE  PREC\n", file = filename, append = TRUE)
  qqcat("#FORCE_TYPE  TMAX\n", file = filename, append = TRUE)
  qqcat("#FORCE_TYPE  TMIN\n", file = filename, append = TRUE)
  qqcat("#FORCE_TYPE  WIND\n", file = filename, append = TRUE)
  qqcat("#FORCE_FORMAT    ASCII\n", file = filename, append = TRUE)
  qqcat("#FORCE_DT    24\n", file = filename, append = TRUE)
  qqcat("#FORCEYEAR   2013\n", file = filename, append = TRUE)
  qqcat("#FORCEMONTH  09\n", file = filename, append = TRUE)
  qqcat("#FORCEDAY    01\n", file = filename, append = TRUE)
  qqcat("#FORCEHOUR   00\n", file = filename, append = TRUE)
  qqcat("#GRID_DECIMAL	4\n", file = filename, append = TRUE)
  qqcat("#FORCING2    FALSE\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#FORCING1	/home/jmg/Projects/VIC_MTCLIM/test_case/forcing/data_	# Forcing file path and prefix\n", file = filename, append = TRUE)
  qqcat("#FORCE_FORMAT	ASCII	# BINARY or ASCII\n", file = filename, append = TRUE)
  qqcat("#N_TYPES		4	# Number of variables (columns)\n", file = filename, append = TRUE)
  qqcat("#FORCE_TYPE	PREC\n", file = filename, append = TRUE)
  qqcat("#FORCE_TYPE	TMAX\n", file = filename, append = TRUE)
  qqcat("#FORCE_TYPE	TMIN\n", file = filename, append = TRUE)
  qqcat("#FORCE_TYPE	WIND\n", file = filename, append = TRUE)
  qqcat("#FORCE_DT	24	# Forcing time step length (hours)\n", file = filename, append = TRUE)
  qqcat("#FORCEYEAR	1997	# Year of first forcing record\n", file = filename, append = TRUE)
  qqcat("#FORCEMONTH	10	# Month of first forcing record\n", file = filename, append = TRUE)
  qqcat("#FORCEDAY	01	# Day of first forcing record\n", file = filename, append = TRUE)
  qqcat("#FORCEHOUR	00	# Hour of first forcing record\n", file = filename, append = TRUE)
  qqcat("#GRID_DECIMAL	4	# Number of digits after decimal point in forcing file names\n", file = filename, append = TRUE)
  qqcat("#WIND_H          10.0    # height of wind speed measurement (m)\n", file = filename, append = TRUE)
  qqcat("#MEASURE_H       2.0     # height of humidity measurement (m)\n", file = filename, append = TRUE)
  qqcat("#ALMA_INPUT	FALSE	# TRUE = ALMA-compliant input variable units; FALSE = standard VIC units\n", file = filename, append = TRUE)
  qqcat("#FORCING2    FALSE\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("FORCING1	@{path_sim}/forcing/data_\n", file = filename, append = TRUE)
  qqcat("GRID_DECIMAL	5\n", file = filename, append = TRUE)
  qqcat("N_TYPES		4\n", file = filename, append = TRUE)
  qqcat("FORCE_TYPE	PREC      SIGNED 100    \n", file = filename, append = TRUE)
  qqcat("FORCE_TYPE	TMIN      SIGNED   100\n", file = filename, append = TRUE)
  qqcat("FORCE_TYPE	TMAX      SIGNED   100\n", file = filename, append = TRUE)
  qqcat("FORCE_TYPE	WIND      SIGNED  100\n", file = filename, append = TRUE)
  qqcat("FORCE_FORMAT	BINARY	\n", file = filename, append = TRUE)
  qqcat("FORCE_ENDIAN    LITTLE \n", file = filename, append = TRUE)
  qqcat("FORCE_DT	24	\n", file = filename, append = TRUE)
  qqcat("FORCEYEAR	@{syear}	\n", file = filename, append = TRUE)
  qqcat("FORCEMONTH	1	\n", file = filename, append = TRUE)
  qqcat("FORCEDAY	1	\n", file = filename, append = TRUE)
  qqcat("FORCEHOUR	01	\n", file = filename, append = TRUE)
  qqcat("WIND_H          10.0    \n", file = filename, append = TRUE)
  qqcat("MEASURE_H       2.0     \n", file = filename, append = TRUE)
  qqcat("ALMA_INPUT	FALSE	\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Land Surface Files and Parameters\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("SOIL            @{path_sim}/params/soil_param	# Soil parameter path/file\n", file = filename, append = TRUE)
  qqcat("ARC_SOIL        FALSE   # TRUE = read soil parameters from ARC/INFO ASCII grids\n", file = filename, append = TRUE)
  qqcat("#SOIL_DIR        (soil param directory)   # Directory containing ARC/INFO ASCII grids of soil parameters - only valid if ARC_SOIL is TRUE\n", file = filename, append = TRUE)
  qqcat("BASEFLOW	NIJSSEN2001	# ARNO = columns 5-8 are the standard VIC baseflow parameters; NIJSSEN2001 = columns 5-8 of soil file are baseflow parameters from Nijssen et al (2001)\n", file = filename, append = TRUE)
  qqcat("JULY_TAVG_SUPPLIED	FALSE	# TRUE = final column of the soil parameter file will contain average July air temperature, for computing treeline; this will be ignored if COMPUTE_TREELINE is FALSE; FALSE = compute the treeline based on the average July air temperature of the forcings over the simulation period\n", file = filename, append = TRUE)
  qqcat("ORGANIC_FRACT	FALSE	# TRUE = simulate organic soils; soil param file contains 3*Nlayer extra columns, listing for each layer the organic fraction, and the bulk density and soil particle density of the organic matter in the soil layer; FALSE = soil param file does not contain any information about organic soil, and organic fraction should be assumed to be 0\n", file = filename, append = TRUE)
  qqcat("VEGLIB	        @{path_sim}/params/veglib_param	# Veg library path/file\n", file = filename, append = TRUE)
  qqcat("VEGPARAM        @{path_sim}/params/veg_param	# Veg parameter path/file\n", file = filename, append = TRUE)
  qqcat("ROOT_ZONES      2	# Number of root zones (must match format of veg param file)\n", file = filename, append = TRUE)
  qqcat("VEGPARAM_LAI 	TRUE    # TRUE = veg param file contains LAI information; FALSE = veg param file does NOT contain LAI information\n", file = filename, append = TRUE)
  qqcat("LAI_SRC 	LAI_FROM_VEGLIB    # LAI_FROM_VEGPARAM = read LAI from veg param file; LAI_FROM_VEGLIB = read LAI from veg library file\n", file = filename, append = TRUE)
  qqcat("SNOW_BAND	1 @{path_sim}/params/elev_band  # Number of snow bands; if number of snow bands > 1, you must insert the snow band path/file after the number of bands (e.g. SNOW_BAND 5 my_path/my_snow_band_file)\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Lake Simulation Parameters\n", file = filename, append = TRUE)
  qqcat("# These need to be un-commented and set to correct values only when running lake model (LAKES is not FALSE)\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("#LAKES		(put lake parameter path/file here)	# Lake parameter path/file\n", file = filename, append = TRUE)
  qqcat("#LAKE_PROFILE	FALSE	# TRUE = User-specified depth-area parameters in lake parameter file; FALSE = VIC computes a parabolic depth-area profile\n", file = filename, append = TRUE)
  qqcat("#EQUAL_AREA	FALSE	# TRUE = grid cells are from an equal-area projection; FALSE = grid cells are on a regular lat-lon grid\n", file = filename, append = TRUE)
  qqcat("#RESOLUTION	0.125	# Grid cell resolution (degrees if EQUAL_AREA is FALSE, km^2 if EQUAL_AREA is TRUE); ignored if LAKES is FALSE\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("# Output Files and Parameters\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("RESULT_DIR      @{path_sim}/results/	# Results directory path\n", file = filename, append = TRUE)
  qqcat("OUT_STEP        0       # Output interval (hours); if 0, OUT_STEP = TIME_STEP\n", file = filename, append = TRUE)
  qqcat("SKIPYEAR 	0	# Number of years of output to omit from the output files\n", file = filename, append = TRUE)
  qqcat("COMPRESS	FALSE	# TRUE = compress input and output files when done\n", file = filename, append = TRUE)
  qqcat("BINARY_OUTPUT @{output_force}	# TRUE = binary output files\n", file = filename, append = TRUE)
  qqcat("ALMA_OUTPUT	FALSE	# TRUE = ALMA-format output files; FALSE = standard VIC units\n", file = filename, append = TRUE)
  qqcat("MOISTFRACT 	FALSE	# TRUE = output soil moisture as volumetric fraction; FALSE = standard VIC units\n", file = filename, append = TRUE)
  qqcat("PRT_HEADER	FALSE   # TRUE = insert a header at the beginning of each output file; FALSE = no header\n", file = filename, append = TRUE)
  qqcat("PRT_SNOW_BAND   FALSE   # TRUE = write a snowband output file, containing band-specific values of snow variables; NOTE: this is ignored if N_OUTFILES is specified below.\n", file = filename, append = TRUE)
  qqcat("\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("# Output File Contents\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("# As of VIC 4.0.6 and 4.1.0, you can specify your output file names and\n", file = filename, append = TRUE)
  qqcat("# contents # in the global param file (see the README.txt file for more\n", file = filename, append = TRUE)
  qqcat("# information).\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("# If you do not specify file names and contents in the global param\n", file = filename, append = TRUE)
  qqcat("# file, VIC will produce the same set of output files that it has\n", file = filename, append = TRUE)
  qqcat("# produced in earlier versions, namely fluxes and snow files, plus\n", file = filename, append = TRUE)
  qqcat("# fdepth files if FROZEN_SOIL is TRUE and snowband files if\n", file = filename, append = TRUE)
  qqcat("# PRT_SNOW_BAND is TRUE.  These files will have the same contents and\n", file = filename, append = TRUE)
  qqcat("# format as in earlier versions.\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("# The OPTIMIZE and LDAS_OUTPUT options have been removed.  These\n", file = filename, append = TRUE)
  qqcat("# output configurations can be selected with the proper set of\n", file = filename, append = TRUE)
  qqcat("# instructions in the global param file.  (see the output.*.template\n", file = filename, append = TRUE)
  qqcat("# files included in this distribution for more information.)\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("# If you do specify the file names and contents in the global param file,\n", file = filename, append = TRUE)
  qqcat("# PRT_SNOW_BAND will have no effect.\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("# Format:\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#   N_OUTFILES    <n_outfiles>\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#   OUTFILE       <prefix>        <nvars>\n", file = filename, append = TRUE)
  qqcat("#   OUTVAR        <varname>       [<format>        <type>  <multiplier>]\n", file = filename, append = TRUE)
  qqcat("#   OUTVAR        <varname>       [<format>        <type>  <multiplier>]\n", file = filename, append = TRUE)
  qqcat("#   OUTVAR        <varname>       [<format>        <type>  <multiplier>]\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#   OUTFILE       <prefix>        <nvars>\n", file = filename, append = TRUE)
  qqcat("#   OUTVAR        <varname>       [<format>        <type>  <multiplier>]\n", file = filename, append = TRUE)
  qqcat("#   OUTVAR        <varname>       [<format>        <type>  <multiplier>]\n", file = filename, append = TRUE)
  qqcat("#   OUTVAR        <varname>       [<format>        <type>  <multiplier>]\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("# where\n", file = filename, append = TRUE)
  qqcat("#   <n_outfiles> = number of output files\n", file = filename, append = TRUE)
  qqcat("#   <prefix>     = name of the output file, NOT including latitude\n", file = filename, append = TRUE)
  qqcat("#                  and longitude\n", file = filename, append = TRUE)
  qqcat("#   <nvars>      = number of variables in the output file\n", file = filename, append = TRUE)
  qqcat("#   <varname>    = name of the variable (this must be one of the\n", file = filename, append = TRUE)
  qqcat("#                  output variable names listed in vicNl_def.h.)\n", file = filename, append = TRUE)
  qqcat("#   <format>     = (for ascii output files) fprintf format string,\n", file = filename, append = TRUE)
  qqcat("#                  e.g.\n", file = filename, append = TRUE)
  qqcat("#                    %.4f = floating point with 4 decimal places\n", file = filename, append = TRUE)
  qqcat("#                    %.7e = scientific notation w/ 7 decimal places\n", file = filename, append = TRUE)
  qqcat("#                    *    = use the default format for this variable\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#   <format>, <type>, and <multiplier> are optional.  For a given\n", file = filename, append = TRUE)
  qqcat("#   variable, you can specify either NONE of these, or ALL of\n", file = filename, append = TRUE)
  qqcat("#   these.  If these are omitted, the default values will be used.\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#   <type>       = (for binary output files) data type code.\n", file = filename, append = TRUE)
  qqcat("#                  Must be one of:\n", file = filename, append = TRUE)
  qqcat("#                    OUT_TYPE_DOUBLE = double-precision floating point\n", file = filename, append = TRUE)
  qqcat("#                    OUT_TYPE_FLOAT  = single-precision floating point\n", file = filename, append = TRUE)
  qqcat("#                    OUT_TYPE_INT    = integer\n", file = filename, append = TRUE)
  qqcat("#                    OUT_TYPE_USINT  = unsigned short integer\n", file = filename, append = TRUE)
  qqcat("#                    OUT_TYPE_SINT   = short integer\n", file = filename, append = TRUE)
  qqcat("#                    OUT_TYPE_CHAR   = char\n", file = filename, append = TRUE)
  qqcat("#                    *               = use the default type\n", file = filename, append = TRUE)
  qqcat("#   <multiplier> = (for binary output files) factor to multiply\n", file = filename, append = TRUE)
  qqcat("#                  the data by before writing, to increase precision.\n", file = filename, append = TRUE)
  qqcat("#                    *    = use the default multiplier for this variable\n", file = filename, append = TRUE)
  qqcat("#\n", file = filename, append = TRUE)
  qqcat("#######################################################################\n", file = filename, append = TRUE)
  
  if (output_force && model == "hbv") {
    qqcat("\n", file = filename, append = TRUE)
    qqcat("N_OUTFILES    1\n", file = filename, append = TRUE)
    qqcat("\n", file = filename, append = TRUE)
    qqcat("OUTFILE       metdata        8 \n", file = filename, append = TRUE)
    qqcat("\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_PREC	* OUT_TYPE_USINT	40\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_AIR_TEMP	* OUT_TYPE_SINT		100\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_SHORTWAVE	* OUT_TYPE_USINT	50\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_LONGWAVE	* OUT_TYPE_USINT	80\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_PRESSURE	* OUT_TYPE_USINT	100\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_QAIR	* OUT_TYPE_USINT	100000\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_VP		* OUT_TYPE_USINT	100\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_WIND	* OUT_TYPE_USINT	100\n", file = filename, append = TRUE)
  }

  if (output_force && model == "fsm") {
    qqcat("\n", file = filename, append = TRUE)
    qqcat("N_OUTFILES    1\n", file = filename, append = TRUE)
    qqcat("\n", file = filename, append = TRUE)
    qqcat("OUTFILE       metdata        8 \n", file = filename, append = TRUE)
    qqcat("\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_RAINF	* OUT_TYPE_USINT	40\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_SNOWF	* OUT_TYPE_USINT	40\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_AIR_TEMP	* OUT_TYPE_SINT		100\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_SHORTWAVE	* OUT_TYPE_USINT	50\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_LONGWAVE	* OUT_TYPE_USINT	80\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_PRESSURE	* OUT_TYPE_USINT	100\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_REL_HUMID	* OUT_TYPE_USINT	100\n", file = filename, append = TRUE)
    qqcat("OUTVAR		OUT_WIND	* OUT_TYPE_USINT	100\n", file = filename, append = TRUE)
  }
  
}


